spring.application.name=websocket-service
server.port=8086
eureka.client.service-url.defaultZone=http://localhost:8081/service-register
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=websocket-group
spring.kafka.consumer.auto-offset-reset=earliest